apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: project
  region: us-west-2

managedNodeGroups:
  - name: project
    instanceType: ["m2.medium", "m3.medium", "m4.medium", "m5.large"]
    # instanceTypes: ["m5.large", "c3.large", "c4.large", "c5.large"]
    desiredCapacity: 1
    spot: true