apiVersion: v1
kind: ClusterConfig

metadata:
  name: project-eks
  region: us-east-1

managedNodeGroups:
  - name: project-eks-ng
    instanceTypes: ["t3.medium", "t3.large", "t3.xlarge"]
    desiredCapacity: 2
    spot: true