apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: project
  region: us-west-1

managedNodeGroups:
  - name: project
    instanceType: m3.medium
    # instanceTypes: ["m5.large", "c3.large", "c4.large", "c5.large"]
    desiredCapacity: 2
    spot: true